#!/usr/bin/env python3
"""Sync open curated links from the vault into the personal site.

Source of truth (edit these, then re-run):
  ~/Work/shared-brain/wiki/concepts/curated-links.md
  ~/Work/shared-brain/wiki/concepts/agentic-engineering-research.md

Output:
  ~/Work/toni-hintikka/src/content/docs/linkit.md

Public only: https URLs. Strips local paths, Ai Lab repo notes, confidence asides.
"""
from __future__ import annotations

import re
from datetime import date
from pathlib import Path

VAULT = Path.home() / "Work/shared-brain/wiki/concepts"
SITE = Path.home() / "Work/toni-hintikka/src/content/docs/linkit.md"

SOURCES = [
    VAULT / "curated-links.md",
    VAULT / "agentic-engineering-research.md",
]

HEADING_FI = {
    "Agentic Engineering / Alignment": "Agentic engineering ja alignment",
    "Uncategorized": "Muut",
    "LLM Gateways & Routing": "LLM-gatewayt ja reititys",
    "LLM-as-a-Judge & Evaluation": "LLM-as-a-Judge ja evaluointi",
    "PR Review & Autonomous CI/CD": "PR-review ja automaatio",
}

CONFIDENCE = re.compile(r"\s*\*?\(Confidence:[^)]+\)\*?\s*\.?", re.I)
LAB_NOTE = re.compile(r"\s*Lab note:[^.]*\.", re.I)
BACKTICK_PATH = re.compile(r"`[^`]*Ai_lab[^`]*`\.?")
ITALIC_CONF = re.compile(r"\s*\*\(Confidence:[^*]*\*\)\.?", re.I)
TRAILING_JUNK = re.compile(r"(\s*\*\*\s*)+$")
MD_LEFTOVER = re.compile(r"\.md`\.?")


def clean_item(text: str) -> str | None:
    if "http://" not in text and "https://" not in text:
        return None
    text = CONFIDENCE.sub("", text)
    text = ITALIC_CONF.sub("", text)
    text = LAB_NOTE.sub("", text)
    text = BACKTICK_PATH.sub("", text)
    text = MD_LEFTOVER.sub("", text)
    text = re.sub(r"\s+", " ", text).strip()
    text = TRAILING_JUNK.sub("", text).strip().rstrip(" .")
    text = re.sub(r"^[\*\-]\s+", "- ", text)
    if not text.startswith("-"):
        text = "- " + text
    if "http://" not in text and "https://" not in text:
        return None
    return text


def parse_sections(path: Path) -> list[tuple[str, list[str]]]:
    if not path.is_file():
        return []
    body = path.read_text(encoding="utf-8")
    if body.startswith("---"):
        end = body.find("\n---", 3)
        if end != -1:
            body = body[end + 4 :]
    sections: list[tuple[str, list[str]]] = []
    current: str | None = None
    items: list[str] = []
    for line in body.splitlines():
        if line.startswith("## "):
            if current and items:
                sections.append((current, items))
            current = line[3:].strip()
            items = []
            continue
        if current is None:
            continue
        if line.startswith("- ") or line.startswith("* "):
            cleaned = clean_item(line)
            if cleaned:
                items.append(cleaned)
    if current and items:
        sections.append((current, items))
    return sections


def main() -> None:
    seen_urls: set[str] = set()
    blocks: list[str] = []
    for src in SOURCES:
        for heading, items in parse_sections(src):
            fi = HEADING_FI.get(heading, heading)
            kept: list[str] = []
            for item in items:
                urls = re.findall(r"https?://[^\s\)]+", item)
                if not urls:
                    continue
                # Dedup only if EVERY url already published (keep section with new links)
                if all(u.rstrip(".,;") in seen_urls for u in urls):
                    continue
                for u in urls:
                    seen_urls.add(u.rstrip(".,;"))
                kept.append(item)
            if kept:
                blocks.append(f"## {fi}\n\n" + "\n".join(kept) + "\n")

    today = date.today().isoformat()
    body = "".join(blocks) if blocks else "*Ei vielä julkisia linkkejä.*\n"
    out = f"""---
title: Linkit
description: Julkinen lukemisto – avoimet artikkelit ja lähteet, luokiteltuna.
---

<!-- Generated by scripts/sync-public-links.py — edit vault curated-links, then re-sync. -->

Valikoituja avoimia linkkejä agentic engineeringiin, deliveryyn ja GenAI-käyttöönottoon. Ei salaista materiaalia. Synkattu vaultista {today}.

{body}
Lista täydentyy. Synkitys guestilla: `cd ~/Work/toni-hintikka && npm run sync-links && npm run deploy`.
"""
    SITE.parent.mkdir(parents=True, exist_ok=True)
    SITE.write_text(out, encoding="utf-8")
    print(f"Wrote {SITE} ({len(seen_urls)} unique URLs)")


if __name__ == "__main__":
    main()
